export const USERNAME_LENGTH_MIN = 3;
export const USERNAME_LENGTH_MAX = 25;
export const FOLDER_LENGTH_MIN = 5;
export const FOLDER_LENGTH_MAX = 50;
export const FOLDER_DESCRIPTION_LENGTH_MIN = 5;
export const FOLDER_DESCRIPTION_LENGTH_MAX = 100;
